"""
investore-agent setup helper.

Usage:
    python setup.py --api https://web-production-4faa7.up.railway.app \
                    --email you@example.com --password 'xxx' \
                    --agent-id home-laptop-01 --mode paper

Effect:
    1. Logs into the InvestOre cloud and gets a short-lived bearer JWT.
    2. Calls /trading/agent/setup which (a) creates an ib_agent
       trading_account row for this (user, agent_id, mode) if missing,
       and (b) mints a 1-year JWT for the agent to authenticate with.
    3. Writes ./.env with the values agent.py needs to run.

Then start the agent with:
    python agent.py
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from urllib.parse import urlparse

import requests


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--api", required=True,
                   help="Cloud API base URL, e.g. https://...railway.app")
    p.add_argument("--email", required=True)
    p.add_argument("--password", required=True)
    p.add_argument("--agent-id", default="default-agent",
                   help="Stable identifier for this machine (e.g. home-laptop-01)")
    p.add_argument("--mode", choices=["paper", "live"], default="paper")
    p.add_argument("--ib-host", default="127.0.0.1")
    p.add_argument("--ib-port", type=int, default=4002,
                   help="4002=paper, 4001=live")
    p.add_argument("--ib-client-id", type=int, default=21)
    p.add_argument("--token-days", type=int, default=365)
    p.add_argument("--out", default=".env",
                   help="Where to write the env file (default: ./.env)")
    args = p.parse_args()

    api = args.api.rstrip("/")

    # 1) Login
    print(f"[1/3] Logging in to {api} ...")
    r = requests.post(
        f"{api}/api/v1/auth/login",
        json={"email": args.email, "password": args.password},
        timeout=15,
    )
    if not r.ok:
        print(f"  login failed: {r.status_code} {r.text}", file=sys.stderr)
        return 2
    bearer = r.json().get("access_token")
    if not bearer:
        print(f"  no access_token in response: {r.text}", file=sys.stderr)
        return 2
    print("  ok")

    # 2) Setup agent
    print(f"[2/3] Setting up agent_id={args.agent_id} mode={args.mode} ...")
    r = requests.post(
        f"{api}/api/v1/trading/agent/setup",
        headers={"Authorization": f"Bearer {bearer}"},
        json={
            "agent_id": args.agent_id,
            "mode": args.mode,
            "token_days": args.token_days,
        },
        timeout=20,
    )
    if not r.ok:
        print(f"  setup failed: {r.status_code} {r.text}", file=sys.stderr)
        return 3
    setup = r.json()
    print(f"  account_id={setup['account_id']} user_id={setup['user_id']}")
    print(f"  ws_url={setup['ws_url']}")

    # 3) Write .env
    env_lines = [
        f"# Generated by investore-agent setup.py",
        f"INVESTORE_API_URL={setup['ws_url']}",
        f"INVESTORE_API_TOKEN={setup['token']}",
        f"INVESTORE_AGENT_ID={args.agent_id}",
        f"IB_HOST={args.ib_host}",
        f"IB_PORT={args.ib_port}",
        f"IB_CLIENT_ID={args.ib_client_id}",
        "",
    ]
    out_path = os.path.abspath(args.out)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(env_lines))
    print(f"[3/3] Wrote {out_path}")
    print()
    print("Next:")
    print(f"  cd {os.path.dirname(out_path) or '.'}")
    print("  # PowerShell:  Get-Content .env | ForEach-Object { if ($_ -match '^([^=#]+)=(.*)$') { Set-Item -Path env:$($matches[1]) -Value $matches[2] } }")
    print("  python agent.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
